buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "GTNH Maven"
            url = "https://nexus.gtnewhorizons.com/repository/public/"
        }
    }
    dependencies {
        classpath 'com.gtnewhorizons.retrofuturegradle:RetroFutureGradle:1.3.+'
    }
}

apply plugin: 'com.gtnewhorizons.retrofuturegradle'

version = "1.1"
group = "net.maa123.ReinforcedBlock" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "ReinforcedBlock"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

minecraft {
    mcVersion = "1.7.10"
    forgeVersion = "10.13.4.1614"
}

dependencies {
}

processResources
{
    // this will ensure that this task is redone when the versions change.
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.mcVersion

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'

        // replace version and mcversion
        expand 'version': project.version, 'mcversion': project.minecraft.mcVersion
    }

    // copy everything else, thats not the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

compileJava {
    options.encoding = 'UTF-8'
}